# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
    # Crucial for enforcing review mechanism
    reviewers:               
      - "your-team-lead"
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "deps"
