name: Code Review

on:
  pull_request:
    branches: [main]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - run: npm run lint --if-present

      - run: npm audit --audit-level=moderate

      - name: Optional: Run static analysis
        run: npm run analyze --if-present
