name: Vercel Deployment Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preview_deployment:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Preview to Vercel
        uses: vercel/actions/deploy@v1 
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          scope: 'preview'

  # Job for Production Deployment on Main branch push
  production_deployment:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    needs: preview_deployment
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Deploy to Vercel Production
        uses: vercel/actions/deploy@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}

          scope: 'production'
