name: Documentation

on:
  push:
    branches: [main]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload your site’s content from the main folder
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
